# Generated by Django 2.2.1 on 2019-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0009_custom_tag_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
