# Generated by Django 2.2.1 on 2019-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0027_webhook_additional_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectchange',
            name='object_repr',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
